export const staticIcons = {
  EditPencil: require('./EditPencil.png'),
  DeleteIcon: require('./delete.png'),
  BackArrow: require('./arrow_back_high_Quality.png'),
  QRCodeScanner: require('./qr_code_scanner.png'),
  PersonAdd: require('./person_add.png'),
  MeasurementTool: require('./home_repair_service.png'),
  Help: require('./live_help.png'),
  RotateCamera: require('./rotate.png'),
  FlipCamera: require('./flip_camera_ios.png'),
  VideoCamOff: require('./videocam_off.png'),
  MicOff: require('./micOff.png'),
  MonitorHeart: require('./monitorHeart.png'),
  nextIcon: require('./nextIcon.png'),
  checkIcon: require('./check.png'),
  checkcircle: require('./check_circle.png'),
  downIcon: require('./down-arrow.png'),
  CheckBoxIcon: require('./check_box.png'),
  BlankCheckBoxIcon: require('./blank_check_box.png'),
  checkCircle: require('./check_circle.png'),
  foundIcon: require('./foundIcon.png'),
  notfoundIcon: require('./notfoundIcon.png'),
  bluetoohIcon: require('./bluetoothIcon.png'),
  bloodGlucoseIcon: require('./bloodGlucoseIcon.png'),
  stopIcon: require('./stopIcon.png'),
  refreshIcon: require('./refreshIcon.png'),
};
