export const Countries = [
  {
    code: 'AD',
    name: 'Andorra',
    phoneCode: '+376',
    regex: '^\\+376\\d{6}$',
  },
  {
    code: 'AE',
    name: 'United Arab Emirates',
    phoneCode: '+971',
    regex: '^\\+971[2-9]\\d{7,8}$',
  },
  {
    code: 'AF',
    name: 'Afghanistan',
    phoneCode: '+93',
    regex: '^\\+93[2-9]\\d{8}$',
  },
  {
    code: 'AG',
    name: 'Antigua and Barbuda',
    phoneCode: '+1-268',
    regex: '^\\+1-268\\d{7}$',
  },
  {
    code: 'AI',
    name: 'Anguilla',
    phoneCode: '+1-264',
    regex: '^\\+1-264\\d{7}$',
  },
  {
    code: 'AL',
    name: 'Albania',
    phoneCode: '+355',
    regex: '^\\+355\\d{8,9}$',
  },
  {
    code: 'AM',
    name: 'Armenia',
    phoneCode: '+374',
    regex: '^\\+374\\d{8}$',
  },
  {
    code: 'AO',
    name: 'Angola',
    phoneCode: '+244',
    regex: '^\\+244\\d{9}$',
  },
  {
    code: 'AQ',
    name: 'Antarctica',
    phoneCode: '+672',
    regex: '^\\+672\\d{6}$',
  },
  {
    code: 'AR',
    name: 'Argentina',
    phoneCode: '+54',
    regex: '^\\+54\\d{10}$',
  },
  {
    code: 'AS',
    name: 'American Samoa',
    phoneCode: '+1-684',
    regex: '^\\+1-684\\d{7}$',
  },
  {
    code: 'AT',
    name: 'Austria',
    phoneCode: '+43',
    regex: '^\\+43\\d{10}$',
  },
  {
    code: 'AU',
    name: 'Australia',
    phoneCode: '+61',
    regex: '^\\+61\\d{9}$',
  },
  {
    code: 'AW',
    name: 'Aruba',
    phoneCode: '+297',
    regex: '^\\+297\\d{7}$',
  },
  {
    code: 'AX',
    name: 'Åland Islands',
    phoneCode: '+358',
    regex: '^\\+358\\d{6,10}$',
  },
  {
    code: 'AZ',
    name: 'Azerbaijan',
    phoneCode: '+994',
    regex: '^\\+994\\d{9}$',
  },
  {
    code: 'BA',
    name: 'Bosnia and Herzegovina',
    phoneCode: '+387',
    regex: '^\\+387\\d{8,9}$',
  },
  {
    code: 'BB',
    name: 'Barbados',
    phoneCode: '+1-246',
    regex: '^\\+1-246\\d{7}$',
  },
  {
    code: 'BD',
    name: 'Bangladesh',
    phoneCode: '+880',
    regex: '^\\+880\\d{10}$',
  },
  {
    code: 'BE',
    name: 'Belgium',
    phoneCode: '+32',
    regex: '^\\+32\\d{8,9}$',
  },
  {
    code: 'BF',
    name: 'Burkina Faso',
    phoneCode: '+226',
    regex: '^\\+226\\d{8}$',
  },
  {
    code: 'BG',
    name: 'Bulgaria',
    phoneCode: '+359',
    regex: '^\\+359\\d{9}$',
  },
  {
    code: 'BH',
    name: 'Bahrain',
    phoneCode: '+973',
    regex: '^\\+973\\d{8}$',
  },
  {
    code: 'BI',
    name: 'Burundi',
    phoneCode: '+257',
    regex: '^\\+257\\d{8}$',
  },
  {
    code: 'BJ',
    name: 'Benin',
    phoneCode: '+229',
    regex: '^\\+229\\d{8}$',
  },
  {
    code: 'BL',
    name: 'Saint Barthélemy',
    phoneCode: '+590',
    regex: '^\\+590\\d{9}$',
  },
  {
    code: 'BM',
    name: 'Bermuda',
    phoneCode: '+1-441',
    regex: '^\\+1-441\\d{7}$',
  },
  {
    code: 'BN',
    name: 'Brunei Darussalam',
    phoneCode: '+673',
    regex: '^\\+673\\d{7}$',
  },
  {
    code: 'BO',
    name: 'Bolivia',
    phoneCode: '+591',
    regex: '^\\+591\\d{8}$',
  },
  {
    code: 'BQ',
    name: 'Caribbean Netherlands',
    phoneCode: '+599',
    regex: '^\\+599\\d{7}$',
  },
  {
    code: 'BR',
    name: 'Brazil',
    phoneCode: '+55',
    regex: '^\\+55\\d{10,11}$',
  },
  {
    code: 'BS',
    name: 'Bahamas',
    phoneCode: '+1-242',
    regex: '^\\+1-242\\d{7}$',
  },
  {
    code: 'BT',
    name: 'Bhutan',
    phoneCode: '+975',
    regex: '^\\+975\\d{7,8}$',
  },
  {
    code: 'BV',
    name: 'Bouvet Island',
    phoneCode: '+47',
    regex: '^\\+47\\d{8}$',
  },
  {
    code: 'BW',
    name: 'Botswana',
    phoneCode: '+267',
    regex: '^\\+267\\d{7,8}$',
  },
  {
    code: 'BY',
    name: 'Belarus',
    phoneCode: '+375',
    regex: '^\\+375\\d{9}$',
  },
  {
    code: 'BZ',
    name: 'Belize',
    phoneCode: '+501',
    regex: '^\\+501\\d{7}$',
  },
  {
    code: 'CA',
    name: 'Canada',
    phoneCode: '+1',
    regex: '^\\+1\\d{10}$',
  },
  {
    code: 'CC',
    name: 'Cocos (Keeling) Islands',
    phoneCode: '+61',
    regex: '^\\+61\\d{9}$',
  },
  {
    code: 'CD',
    name: 'Congo',
    phoneCode: '+243',
    regex: '^\\+243\\d{9}$',
  },
  {
    code: 'CF',
    name: 'Central African Republic',
    phoneCode: '+236',
    regex: '^\\+236\\d{8}$',
  },
  {
    code: 'CG',
    name: 'Republic of the Congo',
    phoneCode: '+242',
    regex: '^\\+242\\d{9}$',
  },
  {
    code: 'CH',
    name: 'Switzerland',
    phoneCode: '+41',
    regex: '^\\+41\\d{9}$',
  },
  {
    code: 'CI',
    name: "Côte d'Ivoire",
    phoneCode: '+225',
    regex: '^\\+225\\d{8}$',
  },
  {
    code: 'CK',
    name: 'Cook Islands',
    phoneCode: '+682',
    regex: '^\\+682\\d{5}$',
  },
  {
    code: 'CL',
    name: 'Chile',
    phoneCode: '+56',
    regex: '^\\+56\\d{9}$',
  },
  {
    code: 'CM',
    name: 'Cameroon',
    phoneCode: '+237',
    regex: '^\\+237\\d{8}$',
  },
  {
    code: 'CN',
    name: 'China',
    phoneCode: '+86',
    regex: '^\\+86\\d{11}$',
  },
  {
    code: 'CO',
    name: 'Colombia',
    phoneCode: '+57',
    regex: '^\\+57\\d{10}$',
  },
  {
    code: 'CR',
    name: 'Costa Rica',
    phoneCode: '+506',
    regex: '^\\+506\\d{8}$',
  },
  {
    code: 'CU',
    name: 'Cuba',
    phoneCode: '+53',
    regex: '^\\+53\\d{8}$',
  },
  {
    code: 'CV',
    name: 'Cape Verde',
    phoneCode: '+238',
    regex: '^\\+238\\d{7}$',
  },
  {
    code: 'CW',
    name: 'Curaçao',
    phoneCode: '+599',
    regex: '^\\+599\\d{7}$',
  },
  {
    code: 'CX',
    name: 'Christmas Island',
    phoneCode: '+61',
    regex: '^\\+61\\d{9}$',
  },
  {
    code: 'CY',
    name: 'Cyprus',
    phoneCode: '+357',
    regex: '^\\+357\\d{8}$',
  },
  {
    code: 'CZ',
    name: 'Czech Republic',
    phoneCode: '+420',
    regex: '^\\+420\\d{9}$',
  },
  {
    code: 'DE',
    name: 'Germany',
    phoneCode: '+49',
    regex: '^\\+49\\d{10}$',
  },
  {
    code: 'DJ',
    name: 'Djibouti',
    phoneCode: '+253',
    regex: '^\\+253\\d{8}$',
  },
  {
    code: 'DK',
    name: 'Denmark',
    phoneCode: '+45',
    regex: '^\\+45\\d{8}$',
  },
  {
    code: 'DM',
    name: 'Dominica',
    phoneCode: '+1-767',
    regex: '^\\+1-767\\d{7}$',
  },
  {
    code: 'DO',
    name: 'Dominican Republic',
    phoneCode: '+1-809',
    regex: '^\\+1-809\\d{7}$',
  },
  {
    code: 'DZ',
    name: 'Algeria',
    phoneCode: '+213',
    regex: '^\\+213\\d{9}$',
  },
  {
    code: 'EC',
    name: 'Ecuador',
    phoneCode: '+593',
    regex: '^\\+593\\d{9}$',
  },
  {
    code: 'EE',
    name: 'Estonia',
    phoneCode: '+372',
    regex: '^\\+372\\d{7,8}$',
  },
  {
    code: 'EG',
    name: 'Egypt',
    phoneCode: '+20',
    regex: '^\\+20\\d{10}$',
  },
  {
    code: 'EH',
    name: 'Western Sahara',
    phoneCode: '+212',
    regex: '^\\+212\\d{9}$',
  },
  {
    code: 'ER',
    name: 'Eritrea',
    phoneCode: '+291',
    regex: '^\\+291\\d{7}$',
  },
  {
    code: 'ES',
    name: 'Spain',
    phoneCode: '+34',
    regex: '^\\+34\\d{9}$',
  },
  {
    code: 'ET',
    name: 'Ethiopia',
    phoneCode: '+251',
    regex: '^\\+251\\d{9}$',
  },
  {
    code: 'EU',
    name: 'Europe',
    phoneCode: '+388',
    regex: '^\\+388\\d{10}$',
  },
  {
    code: 'FI',
    name: 'Finland',
    phoneCode: '+358',
    regex: '^\\+358\\d{8,10}$',
  },
  {
    code: 'FJ',
    name: 'Fiji',
    phoneCode: '+679',
    regex: '^\\+679\\d{7}$',
  },
  {
    code: 'FK',
    name: 'Falkland Islands',
    phoneCode: '+500',
    regex: '^\\+500\\d{5}$',
  },
  {
    code: 'FM',
    name: 'Micronesia',
    phoneCode: '+691',
    regex: '^\\+691\\d{7}$',
  },
  {
    code: 'FO',
    name: 'Faroe Islands',
    phoneCode: '+298',
    regex: '^\\+298\\d{6}$',
  },
  {
    code: 'FR',
    name: 'France',
    phoneCode: '+33',
    regex: '^\\+33\\d{9}$',
  },
  {
    code: 'GA',
    name: 'Gabon',
    phoneCode: '+241',
    regex: '^\\+241\\d{7}$',
  },
  {
    code: 'GB',
    name: 'United Kingdom',
    phoneCode: '+44',
    regex: '^\\+44\\d{10}$',
  },
  {
    code: 'GD',
    name: 'Grenada',
    phoneCode: '+1-473',
    regex: '^\\+1-473\\d{7}$',
  },
  {
    code: 'GE',
    name: 'Georgia',
    phoneCode: '+995',
    regex: '^\\+995\\d{8}$',
  },
  {
    code: 'GF',
    name: 'French Guiana',
    phoneCode: '+594',
    regex: '^\\+594\\d{9}$',
  },
  {
    code: 'GG',
    name: 'Guernsey',
    phoneCode: '+44-1481',
    regex: '^\\+44-1481\\d{6}$',
  },
  {
    code: 'GH',
    name: 'Ghana',
    phoneCode: '+233',
    regex: '^\\+233\\d{9}$',
  },
  {
    code: 'GI',
    name: 'Gibraltar',
    phoneCode: '+350',
    regex: '^\\+350\\d{8}$',
  },
  {
    code: 'GL',
    name: 'Greenland',
    phoneCode: '+299',
    regex: '^\\+299\\d{6}$',
  },
  {
    code: 'GM',
    name: 'Gambia',
    phoneCode: '+220',
    regex: '^\\+220\\d{7}$',
  },
  {
    code: 'GN',
    name: 'Guinea',
    phoneCode: '+224',
    regex: '^\\+224\\d{8}$',
  },
  {
    code: 'GP',
    name: 'Guadeloupe',
    phoneCode: '+590',
    regex: '^\\+590\\d{9}$',
  },
  {
    code: 'GQ',
    name: 'Equatorial Guinea',
    phoneCode: '+240',
    regex: '^\\+240\\d{8}$',
  },
  {
    code: 'GR',
    name: 'Greece',
    phoneCode: '+30',
    regex: '^\\+30\\d{10}$',
  },
  {
    code: 'GS',
    name: 'South Georgia and the South Sandwich Islands',
    phoneCode: '+500',
    regex: '^\\+500\\d{5}$',
  },
  {
    code: 'GT',
    name: 'Guatemala',
    phoneCode: '+502',
    regex: '^\\+502\\d{8}$',
  },
  {
    code: 'GU',
    name: 'Guam',
    phoneCode: '+1-671',
    regex: '^\\+1-671\\d{7}$',
  },
  {
    code: 'GW',
    name: 'Guinea-Bissau',
    phoneCode: '+245',
    regex: '^\\+245\\d{7}$',
  },
  {
    code: 'GY',
    name: 'Guyana',
    phoneCode: '+592',
    regex: '^\\+592\\d{7}$',
  },
  {
    code: 'HK',
    name: 'Hong Kong',
    phoneCode: '+852',
    regex: '^\\+852\\d{8}$',
  },
  {
    code: 'HM',
    name: 'Heard Island and McDonald Islands',
    phoneCode: '+672',
    regex: '^\\+672\\d{6}$',
  },
  {
    code: 'HN',
    name: 'Honduras',
    phoneCode: '+504',
    regex: '^\\+504\\d{8}$',
  },
  {
    code: 'HR',
    name: 'Croatia',
    phoneCode: '+385',
    regex: '^\\+385\\d{9}$',
  },
  {
    code: 'HT',
    name: 'Haiti',
    phoneCode: '+509',
    regex: '^\\+509\\d{8}$',
  },
  {
    code: 'HU',
    name: 'Hungary',
    phoneCode: '+36',
    regex: '^\\+36\\d{9}$',
  },
  {
    code: 'ID',
    name: 'Indonesia',
    phoneCode: '+62',
    regex: '^\\+62\\d{9,11}$',
  },
  {
    code: 'IE',
    name: 'Ireland',
    phoneCode: '+353',
    regex: '^\\+353\\d{9}$',
  },
  {
    code: 'IL',
    name: 'Israel',
    phoneCode: '+972',
    regex: '^\\+972\\d{9}$',
  },
  {
    code: 'IM',
    name: 'Isle of Man',
    phoneCode: '+44-1624',
    regex: '^\\+44-1624\\d{6}$',
  },
  {
    code: 'IN',
    name: 'India',
    phoneCode: '+91',
    regex: '^\\+91\\d{10}$',
  },
  {
    code: 'IO',
    name: 'British Indian Ocean Territory',
    phoneCode: '+246',
    regex: '^\\+246\\d{7}$',
  },
  {
    code: 'IQ',
    name: 'Iraq',
    phoneCode: '+964',
    regex: '^\\+964\\d{10}$',
  },
  {
    code: 'IR',
    name: 'Iran',
    phoneCode: '+98',
    regex: '^\\+98\\d{10}$',
  },
  {
    code: 'IS',
    name: 'Iceland',
    phoneCode: '+354',
    regex: '^\\+354\\d{7}$',
  },
  {
    code: 'IT',
    name: 'Italy',
    phoneCode: '+39',
    regex: '^\\+39\\d{9,10}$',
  },
  {
    code: 'JE',
    name: 'Jersey',
    phoneCode: '+44-1534',
    regex: '^\\+44-1534\\d{6}$',
  },
  {
    code: 'JM',
    name: 'Jamaica',
    phoneCode: '+1-876',
    regex: '^\\+1-876\\d{7}$',
  },
  {
    code: 'JO',
    name: 'Jordan',
    phoneCode: '+962',
    regex: '^\\+962\\d{9}$',
  },
  {
    code: 'JP',
    name: 'Japan',
    phoneCode: '+81',
    regex: '^\\+81\\d{9,10}$',
  },
  {
    code: 'KE',
    name: 'Kenya',
    phoneCode: '+254',
    regex: '^\\+254\\d{9}$',
  },
  {
    code: 'KG',
    name: 'Kyrgyzstan',
    phoneCode: '+996',
    regex: '^\\+996\\d{9}$',
  },
  {
    code: 'KH',
    name: 'Cambodia',
    phoneCode: '+855',
    regex: '^\\+855\\d{8,9}$',
  },
  {
    code: 'KI',
    name: 'Kiribati',
    phoneCode: '+686',
    regex: '^\\+686\\d{5}$',
  },
  {
    code: 'KM',
    name: 'Comoros',
    phoneCode: '+269',
    regex: '^\\+269\\d{7}$',
  },
  {
    code: 'KN',
    name: 'Saint Kitts and Nevis',
    phoneCode: '+1-869',
    regex: '^\\+1-869\\d{7}$',
  },
  {
    code: 'KP',
    name: 'North Korea',
    phoneCode: '+850',
    regex: '^\\+850\\d{9}$',
  },
  {
    code: 'KR',
    name: 'South Korea',
    phoneCode: '+82',
    regex: '^\\+82\\d{9,10}$',
  },
  {
    code: 'KW',
    name: 'Kuwait',
    phoneCode: '+965',
    regex: '^\\+965\\d{8}$',
  },
  {
    code: 'KY',
    name: 'Cayman Islands',
    phoneCode: '+1-345',
    regex: '^\\+1-345\\d{7}$',
  },
  {
    code: 'KZ',
    name: 'Kazakhstan',
    phoneCode: '+7',
    regex: '^\\+7\\d{10}$',
  },
  {
    code: 'LA',
    name: 'Laos',
    phoneCode: '+856',
    regex: '^\\+856\\d{8,9}$',
  },
  {
    code: 'LB',
    name: 'Lebanon',
    phoneCode: '+961',
    regex: '^\\+961\\d{7,8}$',
  },
  {
    code: 'LC',
    name: 'Saint Lucia',
    phoneCode: '+1-758',
    regex: '^\\+1-758\\d{7}$',
  },
  {
    code: 'LI',
    name: 'Liechtenstein',
    phoneCode: '+423',
    regex: '^\\+423\\d{7}$',
  },
  {
    code: 'LK',
    name: 'Sri Lanka',
    phoneCode: '+94',
    regex: '^\\+94\\d{9}$',
  },
  {
    code: 'LR',
    name: 'Liberia',
    phoneCode: '+231',
    regex: '^\\+231\\d{7,8}$',
  },
  {
    code: 'LS',
    name: 'Lesotho',
    phoneCode: '+266',
    regex: '^\\+266\\d{8}$',
  },
  {
    code: 'LT',
    name: 'Lithuania',
    phoneCode: '+370',
    regex: '^\\+370\\d{8}$',
  },
  {
    code: 'LU',
    name: 'Luxembourg',
    phoneCode: '+352',
    regex: '^\\+352\\d{8}$',
  },
  {
    code: 'LV',
    name: 'Latvia',
    phoneCode: '+371',
    regex: '^\\+371\\d{8}$',
  },
  {
    code: 'LY',
    name: 'Libya',
    phoneCode: '+218',
    regex: '^\\+218\\d{9}$',
  },
  {
    code: 'MA',
    name: 'Morocco',
    phoneCode: '+212',
    regex: '^\\+212\\d{9}$',
  },
  {
    code: 'MC',
    name: 'Monaco',
    phoneCode: '+377',
    regex: '^\\+377\\d{8}$',
  },
  {
    code: 'MD',
    name: 'Moldova',
    phoneCode: '+373',
    regex: '^\\+373\\d{8}$',
  },
  {
    code: 'ME',
    name: 'Montenegro',
    phoneCode: '+382',
    regex: '^\\+382\\d{8}$',
  },
  {
    code: 'MF',
    name: 'Saint Martin',
    phoneCode: '+590',
    regex: '^\\+590\\d{9}$',
  },
  {
    code: 'MG',
    name: 'Madagascar',
    phoneCode: '+261',
    regex: '^\\+261\\d{9}$',
  },
  {
    code: 'MH',
    name: 'Marshall Islands',
    phoneCode: '+692',
    regex: '^\\+692\\d{7}$',
  },
  {
    code: 'MK',
    name: 'North Macedonia',
    phoneCode: '+389',
    regex: '^\\+389\\d{8}$',
  },
  {
    code: 'ML',
    name: 'Mali',
    phoneCode: '+223',
    regex: '^\\+223\\d{8}$',
  },
  {
    code: 'MM',
    name: 'Myanmar',
    phoneCode: '+95',
    regex: '^\\+95\\d{9}$',
  },
  {
    code: 'MN',
    name: 'Mongolia',
    phoneCode: '+976',
    regex: '^\\+976\\d{8}$',
  },
  {
    code: 'MO',
    name: 'Macao',
    phoneCode: '+853',
    regex: '^\\+853\\d{8}$',
  },
  {
    code: 'MP',
    name: 'Northern Mariana Islands',
    phoneCode: '+1-670',
    regex: '^\\+1-670\\d{7}$',
  },
  {
    code: 'MQ',
    name: 'Martinique',
    phoneCode: '+596',
    regex: '^\\+596\\d{9}$',
  },
  {
    code: 'MR',
    name: 'Mauritania',
    phoneCode: '+222',
    regex: '^\\+222\\d{8}$',
  },
  {
    code: 'MS',
    name: 'Montserrat',
    phoneCode: '+1-664',
    regex: '^\\+1-664\\d{7}$',
  },
  {
    code: 'MT',
    name: 'Malta',
    phoneCode: '+356',
    regex: '^\\+356\\d{8}$',
  },
  {
    code: 'MU',
    name: 'Mauritius',
    phoneCode: '+230',
    regex: '^\\+230\\d{8}$',
  },
  {
    code: 'MV',
    name: 'Maldives',
    phoneCode: '+960',
    regex: '^\\+960\\d{7}$',
  },
  {
    code: 'MW',
    name: 'Malawi',
    phoneCode: '+265',
    regex: '^\\+265\\d{8}$',
  },
  {
    code: 'MX',
    name: 'Mexico',
    phoneCode: '+52',
    regex: '^\\+52\\d{10}$',
  },
  {
    code: 'MY',
    name: 'Malaysia',
    phoneCode: '+60',
    regex: '^\\+60\\d{9}$',
  },
  {
    code: 'MZ',
    name: 'Mozambique',
    phoneCode: '+258',
    regex: '^\\+258\\d{9}$',
  },
  {
    code: 'NA',
    name: 'Namibia',
    phoneCode: '+264',
    regex: '^\\+264\\d{9}$',
  },
  {
    code: 'NC',
    name: 'New Caledonia',
    phoneCode: '+687',
    regex: '^\\+687\\d{6}$',
  },
  {
    code: 'NE',
    name: 'Niger',
    phoneCode: '+227',
    regex: '^\\+227\\d{8}$',
  },
  {
    code: 'NF',
    name: 'Norfolk Island',
    phoneCode: '+672',
    regex: '^\\+672\\d{6}$',
  },
  {
    code: 'NG',
    name: 'Nigeria',
    phoneCode: '+234',
    regex: '^\\+234\\d{10}$',
  },
  {
    code: 'NI',
    name: 'Nicaragua',
    phoneCode: '+505',
    regex: '^\\+505\\d{8}$',
  },
  {
    code: 'NL',
    name: 'Netherlands',
    phoneCode: '+31',
    regex: '^\\+31\\d{9}$',
  },
  {
    code: 'NO',
    name: 'Norway',
    phoneCode: '+47',
    regex: '^\\+47\\d{8}$',
  },
  {
    code: 'NP',
    name: 'Nepal',
    phoneCode: '+977',
    regex: '^\\+977\\d{10}$',
  },
  {
    code: 'NR',
    name: 'Nauru',
    phoneCode: '+674',
    regex: '^\\+674\\d{7}$',
  },
  {
    code: 'NU',
    name: 'Niue',
    phoneCode: '+683',
    regex: '^\\+683\\d{4}$',
  },
  {
    code: 'NZ',
    name: 'New Zealand',
    phoneCode: '+64',
    regex: '^\\+64\\d{8,9}$',
  },
  {
    code: 'OM',
    name: 'Oman',
    phoneCode: '+968',
    regex: '^\\+968\\d{8}$',
  },
  {
    code: 'PA',
    name: 'Panama',
    phoneCode: '+507',
    regex: '^\\+507\\d{8}$',
  },
  {
    code: 'PE',
    name: 'Peru',
    phoneCode: '+51',
    regex: '^\\+51\\d{8}$',
  },
  {
    code: 'PF',
    name: 'French Polynesia',
    phoneCode: '+689',
    regex: '^\\+689\\d{6}$',
  },
  {
    code: 'PG',
    name: 'Papua New Guinea',
    phoneCode: '+675',
    regex: '^\\+675\\d{7}$',
  },
  {
    code: 'PH',
    name: 'Philippines',
    phoneCode: '+63',
    regex: '^\\+63\\d{10}$',
  },
  {
    code: 'PK',
    name: 'Pakistan',
    phoneCode: '+92',
    regex: '^\\+92\\d{10}$',
  },
  {
    code: 'PL',
    name: 'Poland',
    phoneCode: '+48',
    regex: '^\\+48\\d{9}$',
  },
  {
    code: 'PM',
    name: 'Saint Pierre and Miquelon',
    phoneCode: '+508',
    regex: '^\\+508\\d{6}$',
  },
  {
    code: 'PN',
    name: 'Pitcairn',
    phoneCode: '+870',
    regex: '^\\+870\\d{9}$',
  },
  {
    code: 'PR',
    name: 'Puerto Rico',
    phoneCode: '+1-787',
    regex: '^\\+1-787\\d{7}$',
  },
  {
    code: 'PT',
    name: 'Portugal',
    phoneCode: '+351',
    regex: '^\\+351\\d{9}$',
  },
  {
    code: 'PW',
    name: 'Palau',
    phoneCode: '+680',
    regex: '^\\+680\\d{7}$',
  },
  {
    code: 'PY',
    name: 'Paraguay',
    phoneCode: '+595',
    regex: '^\\+595\\d{9}$',
  },
  {
    code: 'QA',
    name: 'Qatar',
    phoneCode: '+974',
    regex: '^\\+974\\d{8}$',
  },
  {
    code: 'RE',
    name: 'Réunion',
    phoneCode: '+262',
    regex: '^\\+262\\d{9}$',
  },
  {
    code: 'RO',
    name: 'Romania',
    phoneCode: '+40',
    regex: '^\\+40\\d{9}$',
  },
  {
    code: 'RS',
    name: 'Serbia',
    phoneCode: '+381',
    regex: '^\\+381\\d{8}$',
  },
  {
    code: 'RU',
    name: 'Russia',
    phoneCode: '+7',
    regex: '^\\+7\\d{10}$',
  },
  {
    code: 'RW',
    name: 'Rwanda',
    phoneCode: '+250',
    regex: '^\\+250\\d{9}$',
  },
  {
    code: 'SA',
    name: 'Saudi Arabia',
    phoneCode: '+966',
    regex: '^\\+966\\d{9}$',
  },
  {
    code: 'SB',
    name: 'Solomon Islands',
    phoneCode: '+677',
    regex: '^\\+677\\d{5}$',
  },
  {
    code: 'SC',
    name: 'Seychelles',
    phoneCode: '+248',
    regex: '^\\+248\\d{6}$',
  },
  {
    code: 'SD',
    name: 'Sudan',
    phoneCode: '+249',
    regex: '^\\+249\\d{8}$',
  },
  {
    code: 'SE',
    name: 'Sweden',
    phoneCode: '+46',
    regex: '^\\+46\\d{9}$',
  },
  {
    code: 'SG',
    name: 'Singapore',
    phoneCode: '+65',
    regex: '^\\+65\\d{8}$',
  },
  {
    code: 'SH',
    name: 'Saint Helena',
    phoneCode: '+290',
    regex: '^\\+290\\d{4}$',
  },
  {
    code: 'SI',
    name: 'Slovenia',
    phoneCode: '+386',
    regex: '^\\+386\\d{8}$',
  },
  {
    code: 'SJ',
    name: 'Svalbard and Jan Mayen',
    phoneCode: '+47',
    regex: '^\\+47\\d{8}$',
  },
  {
    code: 'SK',
    name: 'Slovakia',
    phoneCode: '+421',
    regex: '^\\+421\\d{9}$',
  },
  {
    code: 'SL',
    name: 'Sierra Leone',
    phoneCode: '+232',
    regex: '^\\+232\\d{8}$',
  },
  {
    code: 'SM',
    name: 'San Marino',
    phoneCode: '+378',
    regex: '^\\+378\\d{6}$',
  },
  {
    code: 'SN',
    name: 'Senegal',
    phoneCode: '+221',
    regex: '^\\+221\\d{9}$',
  },
  {
    code: 'SO',
    name: 'Somalia',
    phoneCode: '+252',
    regex: '^\\+252\\d{7,8}$',
  },
  {
    code: 'SR',
    name: 'Suriname',
    phoneCode: '+597',
    regex: '^\\+597\\d{7}$',
  },
  {
    code: 'SS',
    name: 'South Sudan',
    phoneCode: '+211',
    regex: '^\\+211\\d{9}$',
  },
  {
    code: 'ST',
    name: 'Sao Tome and Principe',
    phoneCode: '+239',
    regex: '^\\+239\\d{7}$',
  },
  {
    code: 'SV',
    name: 'El Salvador',
    phoneCode: '+503',
    regex: '^\\+503\\d{8}$',
  },
  {
    code: 'SX',
    name: 'Sint Maarten',
    phoneCode: '+1-721',
    regex: '^\\+1-721\\d{7}$',
  },
  {
    code: 'SY',
    name: 'Syria',
    phoneCode: '+963',
    regex: '^\\+963\\d{8}$',
  },
  {
    code: 'SZ',
    name: 'Eswatini',
    phoneCode: '+268',
    regex: '^\\+268\\d{8}$',
  },
  {
    code: 'TC',
    name: 'Turks and Caicos Islands',
    phoneCode: '+1-649',
    regex: '^\\+1-649\\d{7}$',
  },
  {
    code: 'TD',
    name: 'Chad',
    phoneCode: '+235',
    regex: '^\\+235\\d{8}$',
  },
  {
    code: 'TF',
    name: 'French Southern Territories',
    phoneCode: '+262',
    regex: '^\\+262\\d{9}$',
  },
  {
    code: 'TG',
    name: 'Togo',
    phoneCode: '+228',
    regex: '^\\+228\\d{8}$',
  },
  {
    code: 'TH',
    name: 'Thailand',
    phoneCode: '+66',
    regex: '^\\+66\\d{9}$',
  },
  {
    code: 'TJ',
    name: 'Tajikistan',
    phoneCode: '+992',
    regex: '^\\+992\\d{9}$',
  },
  {
    code: 'TK',
    name: 'Tokelau',
    phoneCode: '+690',
    regex: '^\\+690\\d{4}$',
  },
  {
    code: 'TL',
    name: 'East Timor',
    phoneCode: '+670',
    regex: '^\\+670\\d{7}$',
  },
  {
    code: 'TM',
    name: 'Turkmenistan',
    phoneCode: '+993',
    regex: '^\\+993\\d{8}$',
  },
  {
    code: 'TN',
    name: 'Tunisia',
    phoneCode: '+216',
    regex: '^\\+216\\d{8}$',
  },
  {
    code: 'TO',
    name: 'Tonga',
    phoneCode: '+676',
    regex: '^\\+676\\d{5}$',
  },
  {
    code: 'TR',
    name: 'Turkey',
    phoneCode: '+90',
    regex: '^\\+90\\d{10}$',
  },
  {
    code: 'TT',
    name: 'Trinidad and Tobago',
    phoneCode: '+1-868',
    regex: '^\\+1-868\\d{7}$',
  },
  {
    code: 'TV',
    name: 'Tuvalu',
    phoneCode: '+688',
    regex: '^\\+688\\d{5}$',
  },
  {
    code: 'TZ',
    name: 'Tanzania',
    phoneCode: '+255',
    regex: '^\\+255\\d{9}$',
  },
  {
    code: 'UA',
    name: 'Ukraine',
    phoneCode: '+380',
    regex: '^\\+380\\d{9}$',
  },
  {
    code: 'UG',
    name: 'Uganda',
    phoneCode: '+256',
    regex: '^\\+256\\d{9}$',
  },
  {
    code: 'US',
    name: 'United States',
    phoneCode: '+1',
    regex: '^\\+1\\d{10}$',
  },
  {
    code: 'UY',
    name: 'Uruguay',
    phoneCode: '+598',
    regex: '^\\+598\\d{8}$',
  },
  {
    code: 'UZ',
    name: 'Uzbekistan',
    phoneCode: '+998',
    regex: '^\\+998\\d{9}$',
  },
  {
    code: 'VA',
    name: 'Vatican',
    phoneCode: '+379',
    regex: '^\\+379\\d{8}$',
  },
  {
    code: 'VC',
    name: 'Saint Vincent and the Grenadines',
    phoneCode: '+1-784',
    regex: '^\\+1-784\\d{7}$',
  },
  {
    code: 'VE',
    name: 'Venezuela',
    phoneCode: '+58',
    regex: '^\\+58\\d{10}$',
  },
  {
    code: 'VG',
    name: 'British Virgin Islands',
    phoneCode: '+1-284',
    regex: '^\\+1-284\\d{7}$',
  },
  {
    code: 'VI',
    name: 'United States Virgin Islands',
    phoneCode: '+1-340',
    regex: '^\\+1-340\\d{7}$',
  },
  {
    code: 'VN',
    name: 'Vietnam',
    phoneCode: '+84',
    regex: '^\\+84\\d{9}$',
  },
  {
    code: 'VU',
    name: 'Vanuatu',
    phoneCode: '+678',
    regex: '^\\+678\\d{7}$',
  },
  {
    code: 'WF',
    name: 'Wallis and Futuna',
    phoneCode: '+681',
    regex: '^\\+681\\d{6}$',
  },
  {
    code: 'WS',
    name: 'Samoa',
    phoneCode: '+685',
    regex: '^\\+685\\d{5}$',
  },
  {
    code: 'YE',
    name: 'Yemen',
    phoneCode: '+967',
    regex: '^\\+967\\d{8}$',
  },
  {
    code: 'YT',
    name: 'Mayotte',
    phoneCode: '+262',
    regex: '^\\+262\\d{9}$',
  },
  {
    code: 'ZA',
    name: 'South Africa',
    phoneCode: '+27',
    regex: '^\\+27\\d{9}$',
  },
  {
    code: 'ZM',
    name: 'Zambia',
    phoneCode: '+260',
    regex: '^\\+260\\d{9}$',
  },
  {
    code: 'ZW',
    name: 'Zimbabwe',
    phoneCode: '+263',
    regex: '^\\+263\\d{9}$',
  },
];
